/**
 * 
 */
package input;

import java.util.Scanner;

import Oracle.Oracle;
import input.Sensor;

import java.io.File;
import java.io.FileNotFoundException;
import java.time.LocalDateTime;

/**
 * @author Maxime Houssin - maxime.houssin@irit.fr
 *	Reads a single sensor file generated by TSimulus to create an ActivationProfile
 */
public class ReaderTSimulus {
	
	/**
	 * Optional : an oracle to store anomalies timestamp and sensor name
	 */
	Oracle oracle;
	
	/**
	 * 
	 * @param filename
	 * 		file containing sensor data
	 * @return sensor
	 * 		a newly created activation profile from a sensor's data
	 */
	public Sensor readFile(String filename) {
		String sensorName = filename.substring(filename.lastIndexOf("/") + 1);
		Sensor sensor = new Sensor(sensorName);
		File file = new File(filename);
		boolean nextIsAnomaly = false;
		
		try {
			Scanner scanner = new Scanner(file);

			while (scanner.hasNextLine()) {
				String line = scanner.nextLine();
				if (line.equals("anomaly")) {
					nextIsAnomaly = true;
					continue;
				}
				
				String lineSplit[] = line.split(";");
				
				String timestampFields[] = lineSplit[0].split("-|\\s|:|\\.");
				LocalDateTime timestamp = LocalDateTime.of( Integer.parseInt(timestampFields[0]), 
															Integer.parseInt(timestampFields[1]), 
															Integer.parseInt(timestampFields[2]), 
															Integer.parseInt(timestampFields[3]), 
															Integer.parseInt(timestampFields[4]), 
															Integer.parseInt(timestampFields[5]));
				
				sensor.addValue(timestamp, Double.valueOf(lineSplit[2]));
				if (nextIsAnomaly) {
					if (oracle != null) {
						oracle.addAnomaly(timestamp);
					}
					nextIsAnomaly = false;
				}
			}
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return sensor;
	}
	
	public void setOracle(Oracle oracle) {
		this.oracle = oracle;
	}
	
	public static void main(String[] args) {
		ReaderTSimulus r = new ReaderTSimulus();
//		Sensor sensor = r.readFile("/home/comhoussin/Documents/These_Maxime_Houssin/Data/Simulated/Test/data_1/data_1");
		Sensor sensor = r.readFile("C:\\Users\\coren\\Desktop\\IRIT\\SANDMAN\\GraphicalInterface_v1.3\\Anomasly\\original_data.xlsx");
		System.out.println(r);
	}
}

